controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

EveryWorkflowFrontPanelBundle:
  resource: '@EveryWorkflowFrontPanelBundle/Resources/config/routes.yaml'

EveryWorkflowAdminPanelBundle:
  resource: '@EveryWorkflowAdminPanelBundle/Resources/config/routes.yaml'

EveryWorkflowBaseBundle:
  resource: "@EveryWorkflowBaseBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowDamBundle:
  resource: "@EveryWorkflowDamBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowCmsBundle:
  resource: "@EveryWorkflowCmsBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowCrmBundle:
  resource: "@EveryWorkflowCrmBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowPimBundle:
  resource: "@EveryWorkflowPimBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowEcommerceBundle:
  resource: "@EveryWorkflowEcommerceBundle/Resources/config/routes.yaml"
  prefix: /api

EveryWorkflowSwaggerBundle:
  resource: "@EveryWorkflowSwaggerBundle/Resources/config/routes.yaml"
